const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const team=require('./team-records'),cloud=require('./cloud-records'),my=require('./my-records'),sync=require('./sync-queue');
const user='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',other='cccccccc-cccc-4ccc-8ccc-cccccccccccc',id=n=>`bbbbbbbb-bbbb-4bbb-8bbb-${String(n).padStart(12,'0')}`;
function fixture(){
 let c={mode:'approved',cloudVerified:true,canUseLocal:true,userId:user,workspaceUserId:user,profile:{id:user,full_name:'Inspector',approved:true,role:'inspector',team:'roadway'},sessionGeneration:1,scopeGeneration:1},online=true,key='account',rows=[],fail=false,reads=0,controller;
 const calls=[];const client={auth:{getUser:async()=>({data:{user:{id:user}}})},from:()=>{const q={then:(a,b)=>{reads++;return Promise.resolve(fail?{error:{code:'500'}}:{data:rows}).then(a,b);}};for(const method of ['select','eq','or','order','limit'])q[method]=(...args)=>{calls.push([method,...args]);return q;};return q;}};
 const o={client,context:()=>c,key:()=>key,online:()=>online,verify:async()=>controller?.verified()};const store=cloud.createStore(o);controller=team.createController({...o,store,changed:()=>{}});
 const row=(n,owner=other)=>({id:id(n),user_id:owner,team:'roadway',inspected_at:'2026-10-05T02:00:00Z',defect_type:'Potholes',expressway:'NLEX',direction:'NB'});
 return {store,controller,calls,row,rows:r=>rows=r,change:x=>c={...c,...x},offline:()=>online=false,reconnect:()=>online=true,key:k=>key=k,fail:()=>fail=true,reads:()=>reads,options:()=>({localEntries:[],page:store.snapshot('team'),context:c,workspaceKey:key,online})};
}
test('Team uses current team without owner predicate and lazy first page does not recursively reload',async()=>{
 const f=fixture();f.rows([f.row(1)]);f.controller.verified();assert.equal(f.reads(),0);f.controller.activate();await new Promise(r=>setTimeout(r,10));f.controller.activate();assert.equal(f.reads(),1);assert.deepEqual(f.calls.filter(c=>c[0]==='eq'),[['eq','team','roadway']]);
});
for(const change of [{mode:'guest'},{mode:'pending'},{cloudVerified:false},{canUseLocal:false},{profile:{id:user,approved:false,role:'inspector',team:'roadway'}},{profile:{id:user,approved:true,role:'administrator',team:null}}])test('unauthorized Team blocked '+JSON.stringify(change),async()=>{
 const f=fixture();f.change(change);await f.controller.load(true);assert.equal(f.reads(),0);assert.equal(f.controller.snapshot().scope,null);
});
test('assigned administrator remains team bounded',async()=>{const f=fixture();f.change({profile:{id:user,approved:true,role:'administrator',team:'roadway'}});f.rows([f.row(1)]);await f.controller.load();assert.deepEqual(f.calls.filter(c=>c[0]==='eq'),[['eq','team','roadway']]);});
test('UUID-only Team projection deduplicates own row, preserves only safe own local context and never grants local actions',async()=>{
 const f=fixture(),own={id:id(2),user_id:user,team:'roadway',sync_status:'pending'},teammate={id:id(1),user_id:other,team:'roadway',sync_status:'pending'},local=[own,teammate];
 f.rows([f.row(2,user),f.row(1)]);await f.controller.load();const o=f.options();o.page={...o.page,rows:[...o.page.rows,o.page.rows[0]]};const before=JSON.stringify(local),r=team.project({...o,localEntries:local}).records;
 assert.equal(r.length,2);assert.equal(r[0].localContext,own);assert.equal(r[1].localContext,null);for(const item of r){assert.equal(item.local,null);assert.equal(item.readOnly,true);assert.equal(sync.isUploadable(item.cloud),false);}assert.equal(JSON.stringify(local),before);
});
test('Team filters use submitted Manila date/type and ignore source/inspector',async()=>{const f=fixture();f.rows([{...f.row(1),inspected_at:'2026-10-04T18:00:00Z'}]);await f.controller.load();assert.equal(team.project(f.options(),{from:'2026-10-05',to:'2026-10-05',source:'mine',inspector:'unknown'}).records.length,1);assert.equal(team.project(f.options(),{type:'Others'}).records.length,0);});
test('My and Team retain separate pages and Team failure leaves My/local unchanged',async()=>{const f=fixture();f.rows([f.row(3,user)]);await f.store.load('my');f.rows([f.row(2)]);await f.controller.load();f.fail();await f.controller.load(true);assert.equal(f.store.snapshot('my').rows[0].id,id(3));assert.equal(f.controller.snapshot().rows[0].id,id(2));assert.equal(f.controller.snapshot().error,'read');});
test('Team bounded five pages 250 rows and atomic refresh',async()=>{const f=fixture();for(let p=0;p<7;p++){f.rows(Array.from({length:51},(_,i)=>f.row(1000-p*50-i)));await f.controller.load(p===0);}assert.equal(f.controller.snapshot().pageCount,5);assert.equal(f.controller.snapshot().rows.length,250);assert.equal(f.controller.snapshot().evicted,true);});
for(const change of [{mode:'signed-out',canUseLocal:false},{userId:other},{sessionGeneration:2},{scopeGeneration:2},{profile:{id:user,approved:true,role:'inspector',team:'other'}},{profile:{id:user,approved:false,role:'inspector',team:'roadway'}}])test('Team invalidates '+JSON.stringify(change),async()=>{const f=fixture();f.rows([f.row(1)]);await f.controller.load();f.change(change);assert.equal(f.controller.records([],{}).records.length,0);assert.equal(f.controller.snapshot().rows.length,0);});
test('offline/workspace invalidation clears Team and reconnect reloads activated view',async()=>{const f=fixture();f.rows([f.row(1)]);await f.controller.load();f.offline();assert.equal(f.controller.snapshot().rows.length,0);f.reconnect();f.controller.verified();await new Promise(r=>setTimeout(r,10));assert.equal(f.controller.snapshot().rows.length,1);f.key('other-workspace');assert.equal(f.controller.snapshot().rows.length,0);});
test('device counts exclude cloud imports and unsaved values; count local durable queue and photo state',()=>{
 const entries=[{id:id(1),sync_status:'pending',photoId:'p',photo_sync_status:'photo_failed'},{id:id(2),sync_status:'synced',remote_id:id(2)},{id:id(3),sync_status:'needs_review'},{id:id(4),sync_status:'pending',cloud_source:true},{id:id(5),sync_status:'pending',importBatchId:'x'},{id:id(6),sync_status:'pending',unsaved:true}];
 assert.deepEqual(team.deviceCounts(entries,e=>!e.unsaved),{waiting:1,submitted:1,review:1,photosOnDevice:1,photosWaiting:1});
});
const html=fs.readFileSync('index.html','utf8'),baseline=require('node:child_process').execFileSync('git',['-c','safe.directory='+process.cwd().replaceAll('\\','/'),'show','HEAD:index.html'],{encoding:'utf8'});
function fn(name){const start=html.indexOf('    function '+name+'(');assert.ok(start>=0);return html.slice(start,html.indexOf('\n    }',start)+6);}
test('five accessible bottom tabs replace Tools and retain footer sizing/safe area CSS',()=>{const nav=html.slice(html.indexOf('<nav class="app-tab-bar"'),html.indexOf('</nav>',html.indexOf('<nav class="app-tab-bar"')));assert.equal((nav.match(/class="app-tab-btn/g)||[]).length,5);assert.match(nav,/id="team-tab"[\s\S]*aria-controls="team-view" data-app-view="team"/);assert.doesNotMatch(nav,/Tools|tools-tab/);assert.equal(html.slice(0,html.indexOf('</style>')),baseline.slice(0,baseline.indexOf('</style>')));assert.match(fn('showAppView'),/aria-selected/);assert.match(html,/ArrowRight[\s\S]*ArrowLeft[\s\S]*Home[\s\S]*End/);});
test('all Tools controls migrated once with identical reload handlers and guidance; Guest has no utility gate',()=>{const settings=html.slice(html.indexOf('<section class="app-view settings-view"'),html.indexOf('<nav class="app-tab-bar"'));for(const id of ['dataset-drawer','dataset-state-label','calib-badge','calib-status','calib-reload','ramp-badge','ramp-status','ramp-reload']){assert.match(settings,new RegExp('id="'+id+'"'));assert.equal((html.match(new RegExp('id="'+id+'"','g'))||[]).length,1);}for(const text of ['add SPOT IT to your home screen','Keep location permission','Works offline with local storage'])assert.ok(settings.includes(text));for(const code of ["document.getElementById('calib-reload').addEventListener('click', () => loadCalibrationDataset(true));","document.getElementById('ramp-reload').addEventListener('click', () => loadRampDataset(true));"])assert.ok(html.includes(code));assert.doesNotMatch(settings,/cloudAccess|canViewTeamRecords/);assert.doesNotMatch(html,/id="tools-view"|data-app-view="tools"/);});
test('legacy Tools routes and saved state resolve to Settings',()=>{for(const value of ['tools','tools-tab','tools-view'])assert.equal(team.route(value),'settings');assert.match(fn('showAppView'),/SPOTITTeamRecords.route/);assert.match(fn('restoreActiveView'),/SPOTITTeamRecords.route/);});
test('scope switching closes both viewers, clears selection, routes and reuses loaded Team pages',()=>{
 const controls=new Map(),el=id=>controls.get(id)||controls.set(id,{value:'archive'}).get(id);let closed=0,activated=0,shown='';const c={cloudRecordStore:{syncScope:()=>({})},cloudPhotoViewer:{close:()=>closed++},teamPhotoViewer:{close:()=>closed++},submittedDialog:{close:()=>closed++},selectMode:true,selectedEntryIds:new Set(['x']),exitSelectMode:()=>c.selectMode=false,teamRecords:{activate:()=>activated++},document:{getElementById:el},showAppView:v=>shown=v,renderLog:()=>{}};vm.createContext(c);vm.runInContext(fn('switchLogScope'),c);c.switchLogScope('team');assert.equal(c.logRecordScope,'team');assert.equal(c.selectedEntryIds.size,0);assert.equal(shown,'log');assert.equal(closed,3);assert.equal(activated,1);c.switchLogScope('my');assert.equal(c.logRecordScope,'my');assert.match(html,/logRecordScope = 'my'/);
});
test('Team cannot enter local selection/export or map marker pipelines; photo transport remains disabled',()=>{assert.match(fn('visibleEntries'),/logRecordScope === 'team'\) return \[\]/);assert.doesNotMatch(fn('accessibleEntries'),/teamRecords|cloudRecordStore/);assert.match(html,/PHOTO_CLOUD_TRANSPORT_ENABLED = false/);assert.match(html,/id="team-open-my"[\s\S]*id="team-open-team"/);assert.doesNotMatch(html,/channel\(['"]team|Team export|More<\/span>/);assert.match(fn('renderTeamWorkspace'),/team records loaded/);assert.match(fn('renderTeamWorkspace'),/snapshotContains/);assert.doesNotMatch(fn('renderTeamWorkspace'),/email|userId|Supabase|RLS/);assert.match(fs.readFileSync('sw.js','utf8'),/v239/);});
test('loading-only notification updates controls without rebuilding Log or touching Map',()=>{
 let controls=0,workspace=0;const page={scope:{token:'scope'},revision:3,loading:true};
 const c={renderTeamWorkspace:()=>workspace++,renderMyControls:()=>controls++,activeRecordController:()=>({snapshot:()=>page}),logRecordScope:'team',logRegisterView:'log',getLogFilters:()=>({}),lastMyCloudRender:JSON.stringify(['scope',3,'team','log',{}]),authWorkspaceUnlocked:true,SPOTITLocalStore:{snapshotContains:()=>{throw Error('Unexpected rebuild');}}};
 vm.createContext(c);vm.runInContext(fn('renderLog'),c);c.renderLog({cloudOnly:true});assert.equal(controls,1);assert.equal(workspace,1);
});
test('UI invalidation immediately closes both photo viewers/detail and clears Team selection before scheduled redraw',()=>{
 let invalidated=0,closed=0,removed=0,scheduled=0;const c={cloudRecordStore:{invalidate:()=>invalidated++},cloudPhotoViewer:{close:()=>closed++},teamPhotoViewer:{close:()=>closed++},submittedDialog:{close:()=>closed++},logRecordScope:'team',selectMode:true,selectedEntryIds:new Set(['record']),exitSelectMode:()=>c.selectMode=false,renderTeamWorkspace:()=>{},scheduleMyRender:()=>scheduled++,document:{getElementById:()=>({click(){}}),querySelectorAll:()=>[{remove:()=>removed++}]}};
 vm.createContext(c);vm.runInContext(fn('invalidateMyRecords'),c);c.invalidateMyRecords();assert.equal(invalidated,1);assert.equal(closed,3);assert.equal(removed,1);assert.equal(scheduled,1);assert.equal(c.logRecordScope,'my');assert.equal(c.selectedEntryIds.size,0);
});
